
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg3NzQ0","is_bot":false,"login":"rdoumeth","name":""},"headRefName":"Roberto-MenuItemReview-Form","number":83,"title":"Add MenuItemReview form and tests ","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/83"},{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karan-UCSBOrganization-fixtures","number":82,"title":"Add Fixtures for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/82"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-editpages","number":70,"title":"Edit Pages for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/70"}]
