
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-UCSBDiningCommonsMenuItem-Form","number":71,"title":"Created Form component for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/71"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-editpages","number":70,"title":"Edit Pages for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/70"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-indexpages","number":69,"title":"Index Pages for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/69"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-createpages","number":68,"title":"Create Pages for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/68"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-placeholders","number":67,"title":"Placeholders for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/67"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-table","number":66,"title":"Table component for articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/66"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-form","number":65,"title":"Form component for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/65"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-fixture","number":64,"title":"Added fixtures for articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/64"}]
