
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karan-UCSBOrganization-form","number":95,"title":"Added UCSBOrganization Form, Form test, and Form stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/95"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-form","number":94,"title":"Finished forms and tests for Help Requests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/94"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-updatemain","number":93,"title":"Update Main Branch","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/93"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"dl-RecommendationRequest-backend","number":89,"title":" Form Component for RecommendationRequest plus tests#28","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/89"}]
