
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karan-UCSBOrganization-table","number":99,"title":"Added UCSBOrganization Table, Table test, and Table stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/99"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"dl-RecommendationRequest-createPages","number":97,"title":"Create Page for RecommendationRequest plus tests and stories#31","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/97"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"dl-RecommendationRequest-pages","number":96,"title":"Copy Placeholders for RecommendationRequest pages; add to App.js/AppNavbar.js#30","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/96"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-form","number":94,"title":"Finished forms and tests for Help Requests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/94"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"dl-RecommendationRequest-backend","number":89,"title":"Table and Form Component for RecommendationRequest plus tests#28#29","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/89"}]
