
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg3NzQ0","is_bot":false,"login":"rdoumeth","name":""},"headRefName":"Roberto-MenuItemReview-IndexPage","number":111,"title":"Add MenuItemReviewIndexPage and Tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/111"},{"author":{"id":"MDQ6VXNlcjg2OTg3NzQ0","is_bot":false,"login":"rdoumeth","name":""},"headRefName":"Roberto-MenuItemReview-EditPage","number":110,"title":"Add MenuItemReviewEditPage and Tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/110"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-editpage","number":108,"title":"Edit Page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/108"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-createpage","number":105,"title":"Creates HelpRequests CreatePage and its stories/tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/105"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-placeholder","number":104,"title":"Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/104"}]
