
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karan-UCSBOrganization-index","number":119,"title":"Added UCSBOrganization Create Page, Tests, and Stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/119"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-indexpage","number":118,"title":"Mr help requests indexpage","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/118"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"dl-RecommendationRequest-createPages","number":117,"title":"Index and Edit Page for RecommendationRequest plus tests and stories#32#33","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/117"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-editpage","number":108,"title":"Edit Page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/108"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-createpage","number":105,"title":"Creates HelpRequests CreatePage and its stories/tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-1/pull/105"}]
